# Generated by Django 3.1.4 on 2021-01-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodist', '0003_auto_20210104_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='year',
            field=models.IntegerField(blank=True, default=2021, null=True),
        ),
    ]
