# Generated by Django 3.1.4 on 2021-01-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodist', '0004_collection_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pfp',
            field=models.ImageField(blank=True, default='defaultpfp.png', null=True, upload_to='artists/'),
        ),
    ]
