# Generated by Django 3.1.4 on 2021-01-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiodist', '0010_collectiontrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='kind',
            field=models.CharField(choices=[('Collection', 'collection'), ('Playlist', 'playlist'), ('EP', 'ep'), ('Album', 'album'), ('LP', 'lp'), ('Compilation', 'compilation'), ('Mixtape', 'mixtape')], default='Collection', max_length=25),
        ),
    ]
