# Generated by Django 3.1.4 on 2021-01-04 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiodist', '0012_auto_20210104_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='year',
        ),
        migrations.AddField(
            model_name='collection',
            name='cover',
            field=models.ImageField(blank=True, default='black.jpeg', null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
