# Generated by Django 3.1.4 on 2021-01-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiodist', '0014_auto_20210105_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_commented', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=500)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiodist.artist')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiodist.song')),
            ],
        ),
    ]
